services:
  flutter-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - ":8080"
    stdin_open: true
    tty: true
    networks:
      - net_private

networks:
  net_private:
    external: true
